name: "BIBLE-API"

on:
  push:
    branches:
      - master

jobs:
    cicd:
        runs-on: bible

        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Copy files
            run: |
              sudo cp -rf . /var/www/apps/bible_api
              sudo mkdir -p /var/www/apps/bible_api/public
              sudo mkdir -p /var/www/apps/bible_api/public/book
              sudo chown -R ubuntu:ubuntu /var/www/apps/bible_api/public

          - name: Build and serve
            run: |
              gem install bundler
              bundle config --local deployment true
              bundle install

          - name: Restart server
            run: |
              sudo systemctl restart bible.service